
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook tabUsers;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtReceive;
	private global::Gtk.Label lblUserName;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Entry txtSend;
	private global::Gtk.Button cmdSend;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Talkative#");
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.tabUsers = new global::Gtk.Notebook ();
		this.tabUsers.CanFocus = true;
		this.tabUsers.Name = "tabUsers";
		this.tabUsers.CurrentPage = 0;
		// Container child tabUsers.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtReceive = new global::Gtk.TextView ();
		this.txtReceive.CanFocus = true;
		this.txtReceive.Name = "txtReceive";
		this.txtReceive.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add (this.txtReceive);
		this.tabUsers.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.lblUserName = new global::Gtk.Label ();
		this.lblUserName.Name = "lblUserName";
		this.lblUserName.LabelProp = global::Mono.Unix.Catalog.GetString ("All");
		this.tabUsers.SetTabLabel (this.GtkScrolledWindow, this.lblUserName);
		this.lblUserName.ShowAll ();
		this.vbox1.Add (this.tabUsers);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tabUsers]));
		w3.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtSend = new global::Gtk.Entry ();
		this.txtSend.CanDefault = true;
		this.txtSend.CanFocus = true;
		this.txtSend.Name = "txtSend";
		this.txtSend.IsEditable = true;
		this.txtSend.InvisibleChar = '●';
		this.hbox3.Add (this.txtSend);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtSend]));
		w4.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cmdSend = new global::Gtk.Button ();
		this.cmdSend.CanFocus = true;
		this.cmdSend.Name = "cmdSend";
		this.cmdSend.UseUnderline = true;
		// Container child cmdSend.Gtk.Container+ContainerChild
		global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w6 = new global::Gtk.HBox ();
		w6.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
		w6.Add (w7);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w6.Add (w9);
		w5.Add (w6);
		this.cmdSend.Add (w5);
		this.hbox3.Add (this.cmdSend);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmdSend]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 393;
		this.DefaultHeight = 387;
		this.txtSend.HasDefault = true;
		this.Hide ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.cmdSend.Clicked += new global::System.EventHandler (this.OnCmdSendClicked);
	}
}
